### ISSUE TITLE
Fix upgrading to 1.20

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock-cli#14]
When upgrading from 1.19 to 1.20, the devDependencies in the package.json should be replaced.

OR

We should specify that this is a manual upgrade, but that would make 1.20 a 2.0.0 (breaking version)

What do you think?

**Comment by Wolfr** [comment]
If you cleanly install Bedrock 1.19 using instructions on http://bedrockapp.org/ and then try to run an upgrade to 1.20, it doesn't work at the moment. 

```
(node:9984) UnhandledPromiseRejectionWarning: Error: Command failed: cp -rn .bedrock-tmp/base/content/docs/templates/ ./content/docs/templates/
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at contentTemplatesIfNecessary (/usr/local/lib/node_modules/bedrock-cli/src/lib/upgrade.js:46:7)
    at /usr/local/lib/node_modules/bedrock-cli/src/lib/upgrade.js:75:5
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:9984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
