### ISSUE TITLE
Bedrock init [template] is broken

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock-cli#6]
Bedrock init [template] is broken

```Johans-MacBook-Pro-2:testbcli johanronsse$ bedrock init bootstrap
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/johanronsse/Sites/testbcli/bedrock.config.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/bedrock-cli/src/lib/migrate-to-pug.js:15:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)```

**Comment by Wolfr** [comment]
@thomastuts with the Bedrock bases coming, we need to take a new look at this one.

What would be cool is to fix up the bedrock cli with some new features

* `bedrock upgrade --dev` - pull changes from the develop branch instead
* `bedrock init` make this work again and ask which Bedrock base you want to use
